import "./globals.css";
import { Inter } from "next/font/google";
import Box from "@mui/material/Box";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center bg-gray-500">
          <Box className="p-2.5 bg-white w-96 h-screen">{children}</Box>
        </div>
      </body>
    </html>
  );
}
